@baseUrl = http://localhost:3000

### SERVER CHECK
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Test User"
}

### CREATE TASK
POST {{baseUrl}}/task
Content-Type: application/json

{
  "title": "First Task",
  "description": "Testing REST Client",
  "priority": "MEDIUM"
}

### LIST TASKS
GET {{baseUrl}}/task

### GET SINGLE TASK
GET {{baseUrl}}/task/TASK_ID

### STATUS TODO -> IN_PROGRESS
PATCH {{baseUrl}}/task/TASK_ID/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### STATUS IN_PROGRESS -> DONE
PATCH {{baseUrl}}/task/TASK_ID/status
Content-Type: application/json

{
  "status": "DONE"
}

### INVALID TRANSITION
PATCH {{baseUrl}}/task/TASK_ID/status
Content-Type: application/json

{
  "status": "TODO"
}

### DELETE TASK (only if DONE)
DELETE {{baseUrl}}/task/TASK_ID

### VERIFY SOFT DELETE
GET {{baseUrl}}/task

### FETCH DELETED TASK
GET {{baseUrl}}/task/TASK_ID

###TEST URL
GET http://localhost:3000/task

### CHECKING EXISTING USERS
POST http://localhost:3000/task
Content-Type: application/json

{
  "title": "Task 1",
  "priority": "MEDIUM"
}